# Generated by Django 5.2.17 on 2026-08-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='telegram',
            field=models.CharField(blank=True, help_text="Foydalanuvchi nomi (@bilan yoki bilarsiz) yoki to'liq t.me/... havola", max_length=100),
        ),
    ]
