# Generated by Django 5.1.15 on 2026-08-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Foydalanuvchi'), ('pharmacy_staff', 'Dorixona xodimi')], default='user', max_length=20),
        ),
    ]
