# Generated by Django 5.2.17 on 2026-08-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
