"""initial schema

Revision ID: 7ccbde91b2ed
Revises: 
Create Date: 2026-08-30 15:23:42.991791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7ccbde91b2ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # geoalchemy2 `geom` ustuni yaratilganda GIST indexni (idx_pharmacies_geom)
    # avtomatik o'zi yaratadi — qo'lda qo'shsak duplicate xato beradi.
    op.create_table('substances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_inn', sa.String(length=255), nullable=False),
    sa.Column('name_uz', sa.String(length=255), nullable=True),
    sa.Column('name_ru', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_substances_name_inn'), 'substances', ['name_inn'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('user', 'pharmacy_staff', 'admin', name='user_role'), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_foreign_key(
        'fk_pharmacies_created_by_admin_id_users', 'pharmacies', 'users',
        ['created_by_admin_id'], ['id'], ondelete='SET NULL',
    )
    op.create_table('drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=False),
    sa.Column('substance_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('dosage_form', sa.String(length=100), nullable=True),
    sa.Column('dosage_strength', sa.String(length=100), nullable=True),
    sa.Column('reference_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['substance_id'], ['substances.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drugs_trade_name'), 'drugs', ['trade_name'], unique=False)
    op.create_table('pharmacy_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('used_by_user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_invites_token'), 'pharmacy_invites', ['token'], unique=True)
    op.create_table('drug_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('alias_text', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_aliases_alias_text'), 'drug_aliases', ['alias_text'], unique=False)
    op.create_table('pharmacy_drug_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pharmacy_id', 'drug_id', name='uq_pharmacy_drug')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # spatial_ref_sys — PostGIS'ning o'z tizim jadvali, tegilmaydi.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    op.drop_table('pharmacy_drug_prices')
    op.drop_index(op.f('ix_drug_aliases_alias_text'), table_name='drug_aliases')
    op.drop_table('drug_aliases')
    op.drop_index(op.f('ix_pharmacy_invites_token'), table_name='pharmacy_invites')
    op.drop_table('pharmacy_invites')
    op.drop_index(op.f('ix_drugs_trade_name'), table_name='drugs')
    op.drop_table('drugs')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_constraint('fk_pharmacies_created_by_admin_id_users', 'pharmacies', type_='foreignkey')
    op.drop_table('users')
    op.drop_index(op.f('ix_substances_name_inn'), table_name='substances')
    op.drop_table('substances')
    op.drop_table('pharmacies')
    # ### end Alembic commands ###
