# Generated by Django 5.2.17 on 2026-09-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_pricedropalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Ikonka nomi (catalog/templatetags/ui_extras.py dagi _ICONS lug'atidan), masalan 'pill'", max_length=20),
        ),
    ]
